name: paivbio_env
channels:
  - defaults
dependencies:
  - ca-certificates=2023.05.30
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.8.16
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - certifi==2023.5.7
    - charset-normalizer==3.2.0
    - filelock==3.12.2
    - idna==3.4
    - jinja2==3.1.2
    - markupsafe==2.1.3
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.24.4
    - pillow==10.0.0
    - requests==2.31.0
    - sympy==1.12
    - torch==2.0.1
    - torchvision==0.15.2
    - typing-extensions==4.7.1
    - urllib3==2.0.3
    - scikit-learn==1.3.0
